language: node_js
node_js:
  - '0.10'
  - '0.11'

env:
  global:
    - CGMINER_HOST=localhost
    - CGMINER_PORT=4028

before_install:
  - rm -rf ~/.cgminer
  - sudo apt-get install libcurl4-openssl-dev libncurses5-dev pkg-config libtool yasm
    autogen automake
  - wget https://github.com/ckolivas/cgminer/tarball/v2.11.4
  - mkdir cgminer
  - tar zxvf v2.11.4 --directory cgminer
  - cd cgminer/ckolivas-cgminer-96c8ff5
  - ./autogen.sh --disable-opencl --disable-adl --enable-cpumining
  - CFLAGS="-O2 -Wall -march=native" ./configure --disable-opencl --disable-adl --enable-cpumining
  - make -j16
  - sudo make install
  - ./cgminer -o stratum+tcp://stratum.mining.eligius.st:3334 -u 16GgJNQDHxx2NpjSxgrAAndnSEjBR4uBTt
    -p x --cpu-threads 1 --text-only --api-listen --api-allow W:0/0 --real-quiet &
  - cd ../..
  - sleep 20

after_script:
  - sleep 5

notifications:
  email: false

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: aXABOL9jsFWIkS1I7Obo0Wo5me5goqmG2yBSetaM224Gp2jrguY68J3l94wehkJi2o/KVVkcYeoC1OvNU/AzAKdF/KscvOTUCK3Vnq6AZYWHYnXjR0g++V0o6GIauaPtSV/rR7UwxRvW5bEyJSKVg6GLWpD9YpuaIv51NM+w+Uw=
  on:
    all_branches: true
